# Generated by Django 3.0.6 on 2021-04-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.IntegerField(blank=True)),
                ('tax_number', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=32)),
                ('size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('number_tiles', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=1, max_digits=5)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machining.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('manufacturer', models.CharField(max_length=64)),
                ('type', models.IntegerField(choices=[(1, 'Milling'), (2, 'Lathe')])),
                ('serial_number', models.CharField(max_length=64)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machining.Service')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machining.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('version', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machining.Machine')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machining.Material')),
                ('tool', models.ManyToManyField(to='machining.Tool')),
            ],
        ),
    ]
