# Generated by Django 3.0.6 on 2021-05-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='model3D',
            field=models.FileField(blank=True, upload_to='attachments/models/'),
        ),
    ]
