# Generated by Django 3.0.6 on 2021-05-07 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machining', '0002_element_model3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='model3D',
            field=models.FileField(blank=True, upload_to='models/'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=64)),
                ('type', models.IntegerField(choices=[(1, 'Drawing'), (2, 'Document'), (3, 'G-code')])),
                ('file', models.FileField(blank=True, upload_to='documents/')),
                ('element', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='machining.Element')),
            ],
        ),
    ]
